const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR__CART: "CLEAR__CART",
  TOGGLE__BUY__STATE: "TOGGLE__BUY__STATE",
};

export default CartActionTypes;
