const ProductActionTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCES: "FETCH_COLLECTIONS_SUCCES",
    FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  };
  
  export default ProductActionTypes;
  