const SidenavActionTypes = {
  SET_SUBCONTAINER: "SET_SUBCONTAINER",
  SET_SUBCONTAINER_ENTRIES: "SET_SUBCONTAINER_ENTRIES",
  SET_ENTRY_STORE: "SET_ENTRY_STORE",
  SET_DROPDOWN_ENTRIES: "SET_DROPDOWN_ENTRIES",
};

export default SidenavActionTypes;
